kind: pipeline
type: exec
name: default
clone:
  disable: true

platform:
  os: linux
  arch: amd64

steps:
  - name: run the script
    commands:
      - cd /home/rohit/serverhealthcheck
      - ./gitpush.sh

trigger:
  when:
    - push
    - tag
  branch:
    - main

